domino:
  deployments:
    leaflet:
      source:
        type: DOCKER
        home: "[dsm:common.home.docker]"
        resource: leaflet
      target:
        hosts:
          - psproghu
        multi-instance:
          enabled: true
          instance-count: 2
          spread-mode: replicate
          naming-strategy: custom-predefined
          defined-names:
            - primary
            - standby
          port-offset: 100
          host-network-base-port: 9082
      execution:
        command-name: app_leaflet
        via: STANDARD
        args:
          network-mode: host
          environment:
            APP_ARGS: |
              --spring.profiles.active=production
              --spring.config.location=/opt/leaflet/appconfig_leaflet.yml
              --spring.datasource.username=[dsm:common.mysql.username]
              --spring.datasource.password=[dsm:common.mysql.password]
              --oauth.client-id=[dsm:domino.oauth.psproghu.prod.leaflet.client-id]
              --oauth.client-secret=[dsm:domino.oauth.psproghu.prod.leaflet.client-secret]
          volumes:
            "[dsm:volume.logs]": "/opt/leaflet/logs:rw"
            "[dsm:volume.config.leaflet]": "/opt/leaflet/appconfig_leaflet.yml:ro"
            "[dsm:volume.vfs]": "/opt/leaflet/storage:rw"
            "/etc/timezone": "/etc/timezone:ro"
            "/etc/localtime": "/etc/localtime:ro"
          restart-policy: unless-stopped
      health-check:
        enabled: true
        delay: 20 seconds
        timeout: 2 seconds
        max-attempts: 3
        endpoint: "http://127.0.0.1:9082/api/actuator/info"
      info:
        enabled: true
        endpoint: "https://api.psprog.hu/actuator/info"
        field-mapping:
          abbreviation: $.app.abbreviation
          version: $.build.version
